import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <ClerkProvider>
        <html lang="en">
    
        <body className='bg-hero bg-no-repeat cover bg-black h-[100vh]'>
          <Navbar/>
        {children}
        </body>
        </html>
        </ClerkProvider>
  );
}
